name: Deploy Daggerheart Tracker
name: Deploy Daggerheart Tracker

# Запускать каждый раз, когда делаем push в main
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Получаем код репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # Публикация на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
